spring:
  application:
    name: research
  datasource:
    hc:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbc-url: jdbc:mysql://db.thecoffeebox.vn:3306/devthecoffeebox
      jdbc-url: jdbc:mysql://localhost:3306/devthecoffeebox
      username: devtcb
      password: devtcb
      hikari:
        connection-timeout: 600000